// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWZySvzP7hmxdp7zmm3ZBEPIweCbjHOWg',
    appId: '1:226076386151:web:bd8abd555d1738ed7885c2',
    messagingSenderId: '226076386151',
    projectId: 'clusty',
    authDomain: 'clusty.firebaseapp.com',
    storageBucket: 'clusty.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZOjkBhL_gH48aJZPWPZIdMkDp8fByKXw',
    appId: '1:226076386151:android:fc91f56743d68a797885c2',
    messagingSenderId: '226076386151',
    projectId: 'clusty',
    storageBucket: 'clusty.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFVnaXKvrHmeW_q30cfQmAsO7-UA-kSsU',
    appId: '1:226076386151:ios:71a2cb3b4f4e03e97885c2',
    messagingSenderId: '226076386151',
    projectId: 'clusty',
    storageBucket: 'clusty.appspot.com',
    iosBundleId: 'com.stf.clusty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFVnaXKvrHmeW_q30cfQmAsO7-UA-kSsU',
    appId: '1:226076386151:ios:71a2cb3b4f4e03e97885c2',
    messagingSenderId: '226076386151',
    projectId: 'clusty',
    storageBucket: 'clusty.appspot.com',
    iosBundleId: 'com.stf.clusty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWZySvzP7hmxdp7zmm3ZBEPIweCbjHOWg',
    appId: '1:226076386151:web:27b62b87a5bdde147885c2',
    messagingSenderId: '226076386151',
    projectId: 'clusty',
    authDomain: 'clusty.firebaseapp.com',
    storageBucket: 'clusty.appspot.com',
  );
}
